import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.scss';
import Header from '@/components/header/header';

const lato = Lato({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} base-grid main-layout`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
